version: '3'
services:
  udagram-user:
    build:
      context: ../../udagram-api-user
      dockerfile: Dockerfile
    image: mestrefox/udagram-user-api
  udagram-feed:
    build:
      context: ../../udagram-api-feed
      dockerfile: Dockerfile
    image: mestrefox/udagram-feed
 