apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api
  labels:
    service: udagram-feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-feed-api
  template:
    metadata:
      labels:
        service: udagram-feed-api
    spec:
      containers:
      - name: udagram-feed-api
        image: mestrefox/udagram-feed-api:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
            
      restartPolicy: Always
