apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-user
  labels:
    service: udagram-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-user
  template:
    metadata:
      labels:
        service: udagram-user
    spec:
      containers:
      - name: udagram-user
        image: mestrefox/udagram-user-api:latest
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"      
     
      restartPolicy: Always